environments:
  test: [synthetic_crisis, real_covid]
real_covid:
  source: ${real_data_anchor.file_test_covid}
probes:
  cost_stress:
    enable: true
    fee_multiplier: 1.5
  drop_spurious_vol:
    enable: true
