data:
  source: "real"
  anchors:
    - { name: "train_2017", split: "train", start: "2017-01-03", end: "2017-12-29" }
    - { name: "train_2018", split: "train", start: "2018-01-02", end: "2018-09-28" }
    - { name: "train_2019", split: "train", start: "2019-01-02", end: "2019-12-31" }
    - { name: "val_2018_late_spike", split: "val", start: "2018-10-10", end: "2018-11-30" }
    - { name: "test_2018_volmageddon", split: "test", start: "2018-02-01", end: "2018-02-28" }
    - { name: "test_2018_q4_selloff",  split: "test", start: "2018-12-01", end: "2018-12-31" }
    - { name: "test_2020_covid_mj",    split: "test", start: "2020-03-01", end: "2020-06-30" }
    - { name: "test_2022_inflation",   split: "test", start: "2022-04-01", end: "2022-10-31" }

    # - { name: "test_2008_gfc", split: "test", start: "2008-09-01", end: "2009-03-31" }
  symbols:
    underlying: "SPY"
    futures:    "ES"
    options:    "SPY"
  vendor:
    path_csv_root: "data/real/"
  episode:
    days: 60
    stride_days: 5
    tz: "America/New_York"
train:
  seed: 7
