name: invariant-hedging
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.*
  - pandas=2.2.*
  - scipy=1.11.4
  - pytorch=2.3.*
  - matplotlib=3.9.*
  - scikit-learn=1.5.*
  - tqdm=4.66.*
  - pip
  - pip:
      - hydra-core==1.3.2
      - plotly==5.18.0
      - pyyaml==6.0.1
      - wandb==0.16.2
      - opt-einsum==3.3.0
      - pytest==7.4.4
      - ruff==0.1.9
