name: daily
seeds: [0, 1, 2]
compute_per_env_metrics: true
compute_msi: false
msi_batch_size: 512
report:
  alpha: 0.95
  bootstrap_samples: 1000
  table_path: crisis_results.csv
  plot_dir: plots
  include_hourly: true
  checkpoint_path: null

baselines:
  include: [no_hedge, delta]
  table_path: baseline_metrics.csv
