name: high
seeds: [0, 1, 2]
report:
  alpha: 0.95
  bootstrap_samples: 1000
  table_path: high_vol_results.csv
  plot_dir: high_vol_plots
  include_hourly: false
  checkpoint_path: null

baselines:
  include: [no_hedge, delta]
  table_path: high_vol_baselines.csv
