data:
  hourly_episodes: 256
  name: synthetic
  rate: 0.01
  real_data_anchor:
    enabled: true
    file: data/spy_sample.csv
    slippage_bps: 5
  seed: 0
  spot_init: 100.0
  test_episodes: 512
  train_episodes: 2048
  use_jumps: false
  use_liquidity_spread: false
  val_episodes: 512
envs:
  robustness:
    hours_per_day: 6
    rebalancing: hourly
  test:
  - crisis
  train:
  - low
  - med
  val:
  - high
eval:
  baselines:
    include:
    - no_hedge
    - delta
    - delta_gamma
    table_path: baseline_metrics.csv
  compute_msi: false
  compute_per_env_metrics: true
  msi_batch_size: 512
  msi_feature_groups:
    invariants: []
    spurious: []
  name: daily
  report:
    alpha: 0.95
    bootstrap_samples: 1000
    checkpoint_path: null
    include_hourly: true
    plot_dir: plots
    table_path: crisis_results.csv
  seeds:
  - 0
  - 1
  - 2
logging:
  eval_interval: 20
  local_mirror:
    artifacts_dir: artifacts
    base_dir: reports/artifacts
    checkpoints_dir: checkpoints
    config_file: config.yaml
    enabled: true
    final_metrics_file: final_metrics.json
    metrics_file: metrics.jsonl
    stats_csv: stats.csv
  log_interval: 100
  wandb:
    dir: reports/wandb
    enabled: false
    entity: null
    offline_ok: true
    project: invariant-hedging
loss:
  cvar_alpha: 0.95
  name: cvar
model:
  adapter_hidden: 16
  dropout: 0.0
  hidden_depth: 3
  hidden_width: 192
  layer_norm: false
  max_position: 5.0
  name: erm
  objective: erm
  representation_dim: 64
  use_prev_position: true
optimizer:
  lr: 0.0001
  name: adamw
  weight_decay: 1.0e-06
scheduler:
  name: cosine
  warmup_steps: 1000
train:
  batch_size: 128
  checkpoint_topk: 1
  eval_interval: 20
  grad_clip: 1.0
  irm_ramp_steps: 20
  max_trade_warning_factor: 1.2
  pretrain_steps: 20
  seed: 0
  steps: 100
