name: erm_reg
objective: erm
hidden_width: 256
hidden_depth: 3
dropout: 0.2
layer_norm: true
max_position: 5.0
use_prev_position: true
representation_dim: 64
adapter_hidden: 16
regularization:
  weight_decay: 1.0e-5
  label_smoothing: 0.05
