name: irm
objective: irm
hidden_width: 192
hidden_depth: 3
dropout: 0.0
layer_norm: true
max_position: 5.0
use_prev_position: true
representation_dim: 64
adapter_hidden: 16
irm:
  penalty_weight: 1.0
