episode:
  length_days: 60
  rebalancing: daily
  notional: 1.0

dynamics:
  model: heston
  params:
    mu: -0.05
    long_term_var: 0.45
    mean_rev: 0.25
    vol_of_vol: 0.6
    rho: -0.7
    v0: 0.6

costs:
  file: crisis

options:
  strike_mode: atm
  maturity_days: 60
  rate: 0.005
