device: auto
precision: float32
total_steps: 150000
batch_size: ${data.batch_size}
log_interval: 200
eval_interval: 5000
save_interval: 25000
optimizer:
  name: adam
  lr: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8
scheduler:
  name: cosine
  warmup_steps: 2000
  min_lr: 1e-5
clip_grad_norm: 1.0
seed: ${project.seed}
