# @package _global_

defaults:
  - /data: synthetic
  - /envs: daily
  - /model: erm
  - /eval: daily
  - /logging: default
  - _self_

runtime:
  seed: 0
  device: auto

eval:
  name: paper
  seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
  horizons: [20, 60, 120]
  evaluation_windows:
    - name: crisis_2018_volmageddon
      split: spy_test_2018
      start_date: "2018-02-01"
      end_date: "2018-02-28"
    - name: crisis_2020_covid
      split: spy_test_2020
      start_date: "2020-02-15"
      end_date: "2020-04-15"
    - name: crisis_2022_inflation
      split: spy_test_2022
      start_date: "2022-06-01"
      end_date: "2022-10-31"
  anchors:
    - name: crisis_2008_gfc
      split: spy_test_2008
      start_date: "2008-09-01"
      end_date: "2009-03-31"
  report:
    alpha: 0.95
    bootstrap_samples: 1000
    table_path: paper_crisis_metrics.csv
    plot_dir: paper_plots
    include_hourly: true
    checkpoint_path: null
  baselines:
    include: [no_hedge, delta]
    table_path: paper_baselines.csv

paper:
  data_config: configs/paper/data.yaml
  methods_config: configs/paper/methods.yaml
  summary: "Evaluation entry point mirroring the paper's crisis sweeps."
