# @package _global_

defaults:
  - /train: erm
  - _self_

runtime:
  seed: 0
  device: auto
  mixed_precision: true

train:
  seed: 0
  steps: 150000
  pretrain_steps: 20000
  irm_ramp_steps: 10000
  eval_interval: 1000
  checkpoint_topk: 3
  seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

optimizer:
  name: adamw
  lr: 1.0e-4
  weight_decay: 1.0e-6

scheduler:
  name: cosine
  warmup_steps: 1000

paper:
  data_config: configs/paper/data.yaml
  methods_config: configs/paper/methods.yaml
  summary: "Hydra entry point for the paper's training defaults."
