#!/usr/bin/env bash
set -euo pipefail

CONFIG=${1:-train/erm}
shift || true

export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}
export MKL_THREADING_LAYER=${MKL_THREADING_LAYER:-SEQUENTIAL}
export KMP_AFFINITY=${KMP_AFFINITY:-disabled}
export KMP_INIT_AT_FORK=${KMP_INIT_AT_FORK:-FALSE}
export HIRM_TORCH_NUM_THREADS=${HIRM_TORCH_NUM_THREADS:-$OMP_NUM_THREADS}
export PYTHONHASHSEED=${PYTHONHASHSEED:-0}
export CUBLAS_WORKSPACE_CONFIG=${CUBLAS_WORKSPACE_CONFIG:-:4096:8}
export CUDNN_DETERMINISTIC=${CUDNN_DETERMINISTIC:-1}
export CUDA_LAUNCH_BLOCKING=${CUDA_LAUNCH_BLOCKING:-1}
export NUMPY_DEFAULT_DTYPE=${NUMPY_DEFAULT_DTYPE:-float64}
export PYTORCH_ENABLE_MPS_FALLBACK=${PYTORCH_ENABLE_MPS_FALLBACK:-1}
export WANDB_MODE=${WANDB_MODE:-disabled}
export WANDB_DISABLED=${WANDB_DISABLED:-true}
export PYTHONPATH="$PWD/src${PYTHONPATH:+:$PYTHONPATH}"

python3 experiments/run_train.py --config-name="${CONFIG}" "$@"
