name: CI Smoke
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ stabilize/ci-baseline ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint
        run: |
          ruff check .
          ruff format --check .

      - name: Unit tests and tiny train
        run: make ci-smoke

      - name: Upload smoke artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-smoke-artifacts
          path: |
            runs/ci_smoke/**
            .pytest_cache/**
