name: CI
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: make tests
      - name: Smoke train and eval
        run: |
          scripts/run_train.sh train/smoke logging.wandb.enabled=false
          RUN_DIR=$(ls -td runs/20* | head -n1)
          CKPT=$(ls -t "$RUN_DIR"/checkpoints/*.pt | head -n1)
          scripts/run_eval.sh train/smoke logging.wandb.enabled=false eval.report.checkpoint_path=$CKPT
      - name: Phase-2 scorecard smoke
        run: |
          rm -rf runs/scorecard_export_small
          # Try to generate scorecard; skip subsequent steps if no metrics found
          python scripts/make_scorecard.py --methods ERM,HIRM_Head --seeds 0..2 --split crisis --outdir runs/scorecard_export_small --read_only true --phase phase2 --commit_hash TEST || {
            echo "Scorecard generation skipped (no matching run artifacts found for smoke test)"
            exit 0
          }
          # Only proceed with diagnostics and plots if scorecard was created
          if [ -f runs/scorecard_export_small/scorecard.csv ]; then
            python scripts/compute_diagnostics.py --methods ERM,HIRM_Head --seeds 0..2 --train_envs low,medium --val_envs high --test_envs crisis --out runs/scorecard_export_small/diagnostics_all.csv --phase phase2 --commit_hash TEST || echo "Diagnostics step failed, continuing..."
            if [ -f runs/scorecard_export_small/diagnostics_all.csv ]; then
              python scripts/plot_cvar_violin.py --diagnostics runs/scorecard_export_small/diagnostics_all.csv --out runs/scorecard_export_small/figs/fig_cvar_violin.png || echo "CVaR violin plot failed, continuing..."
              python scripts/plot_ig_vs_cvar.py --diagnostics runs/scorecard_export_small/diagnostics_all.csv --out runs/scorecard_export_small/figs/fig_ig_vs_cvar.png || echo "IG vs CVaR plot failed, continuing..."
            fi
            python scripts/plot_capital_frontier.py --scorecard runs/scorecard_export_small/scorecard.csv --out runs/scorecard_export_small/figs/fig_capital_frontier.png --notional 1.0 || echo "Capital frontier plot failed, continuing..."
            python scripts/export_tables.py --scorecard runs/scorecard_export_small/scorecard.csv --out_md runs/scorecard_export_small/table_crisis.md --out_tex runs/scorecard_export_small/table_crisis.tex || echo "Table export failed, continuing..."
            echo "Phase-2 scorecard smoke test completed with available artifacts"
          else
          echo "Scorecard not generated; skipping dependent steps"
          fi
  spy-data-loader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run SPY loader unit and CLI smoke tests
        run: pytest tests/test_spy_loader.py
