name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: make tests
      - name: Smoke train and eval
        run: |
          scripts/run_train.sh train/smoke logging.wandb.enabled=false
          RUN_DIR=$(ls -td runs/20* | head -n1)
          CKPT=$(ls -t "$RUN_DIR"/checkpoints/*.pt | head -n1)
          scripts/run_eval.sh train/smoke logging.wandb.enabled=false eval.report.checkpoint_path=$CKPT
